In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('fortune 1000 companies in 2022 - 2022.csv')
df.info()
df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   rank in 2022                          1000 non-null   object
 1   Name                                  1000 non-null   object
 2   Revenue                               1000 non-null   object
 3   revenue(% change)                     1000 non-null   object
 4   profits in millions                   1000 non-null   object
                     1000 non-null   object
 6   assets                                1000 non-null   object
 7   market value                          1000 non-null   object
 8   change in rank of top 1000 companies  1000 non-null   object
 9   employees                             1000 non-null   object
 10  change in rank(500 only)
            1000 non-null   object
dtypes: object(11)
memory usage: 86.1+ KB

,rank in 2022,Name,Revenue,revenue(% change),profits in millions,profits % change\r,assets,market value,change in rank of top 1000 companies,employees,change in rank(500 only)\r\n
0,1,Walmart,"$572,754",2.40%,"$13,673",1.20%,"$244,860","$409,795",-,"2,300,000",-
1,2,Amazon,"$469,822",21.70%,"$33,364",56.40%,"$420,549","$1,658,807.30",-,"1,608,000",-
2,3,Apple,"$365,817",33.30%,"$94,680",64.90%,"$351,002","$2,849,537.60",-,"154,000",-
3,4,CVS Health,"$292,111",8.70%,"$7,910",10.20%,"$232,999","$132,839.20",-,"258,000",-
4,5,UnitedHealth Group,"$287,597",11.80%,"$17,285",12.20%,"$212,206","$479,830.30",-,"350,000",-
...,...,...,...,...,...,...,...,...,...,...,...
995,996,Vizio Holding,"$2,124",4%,-$39.40,-138.40%,$935.80,"$1,705.10",-,800,-
996,997,1-800-Flowers.com,"$2,122.20",42.50%,$118.70,101.10%,"$1,076.70",$830,-,"4,800",-
997,998,Cowen,"$2,112.80",30.20%,$295.60,36.60%,"$8,748.80",$744.10,-,"1,534",-
998,999,Ashland Global Holdings,"$2,111",-11.20%,$220,-,"$6,612","$5,601.90",-130,"4,100",-
999,"1,000",DocuSign,"$2,107.20",45%,-$70,-,"$2,541.30","$21,302.80",-,"7,461",-

In [10]:
sorted_df = df.sort_values('market value', ascending = False)
sorted_df = sorted_df[sorted_df['market value'] != '-'].sort_values('market value').reset_index(drop = True)
sorted_df.head(20)

,rank in 2022,Name,Revenue,revenue(% change),profits in millions,profits % change\r,assets,market value,change in rank of top 1000 companies,employees,change in rank(500 only)\r\n
0,807,Calumet Specialty Products Partners,"$3,148",38.80%,-$260.10,-,"$2,127.90","$1,070.80",96,"1,450",-
1,839,Avaya Holdings,"$2,973",3.50%,-$13,-,"$5,985","$1,076",-65,"8,063",-
2,678,Conduent,"$4,140",-0.60%,-$28,-,"$4,036","$1,111.60",-74,"60,000",-
3,65,Tesla,"$53,823",70.70%,"$5,519",665.50%,"$62,131","$1,113,707.80",35,"99,290",35
4,982,Sleep Number,"$2,184.90",17.70%,$153.70,10.50%,$919.50,"$1,123.70",16,"5,388",-
5,919,Griffon,"$2,541.70",5.60%,$79.20,48.30%,"$2,604.70","$1,127.80",-61,"6,700",-
6,498,ARKO,"$6,412.60",88.10%,$59.20,348.90%,"$2,942.30","$1,133.90",183,"11,236",-
7,392,SpartanNash,"$8,931",-4.50%,$73.80,-2.80%,"$2,206.80","$1,185.10",-63,"13,300",-63
8,688,Bright Health Group,"$4,029.40",233.70%,"-$1,184.90",-,"$3,598.30","$1,213.50",-,"3,203",-
9,722,M/I Homes,"$3,745.90",23%,$396.90,65.40%,"$3,239.90","$1,262.20",19,"1,657",-
10,752,Primoris Services,"$3,497.60",0.20%,$115.60,10.10%,"$2,543.30","$1,269.80",-79,"10,810",-
11,700,loanDepot,"$3,943.20",-11.30%,$113.50,-94.40%,"$11,812.30","$1,290.30",-117,"11,307",-
12,885,G-III Apparel Group,"$2,766.50",34.60%,$200.60,752%,"$2,742.50","$1,296.10",64,"3,250",-
13,911,Guess,"$2,591.60",38.10%,$171.40,-,"$2,555.60","$1,305.50",79,"12,500",-
14,891,Brookdale Senior Living,"$2,758.30",-22.10%,-$99.30,-221.10%,"$6,410.50","$1,308.30",-226,"28,545",-
15,909,Steelcase,"$2,596.20",-30.30%,$26.10,-86.90%,"$2,354","$1,339.50",-264,"11,400",-
16,549,Ryerson Holding,"$5,675.30",63.70%,$294.30,-,"$2,365.60","$1,344.60",127,"4,000",-
17,916,BrightView Holdings,"$2,553.60",8.80%,$46.30,-,"$3,237.60","$1,351.50",-32,"20,150",-
18,855,PC Connection,"$2,892.60",11.70%,$69.90,25.40%,"$1,083.40","$1,375.80",-38,"2,542",-
19,685,Patrick Industries,"$4,078.10",64%,$224.90,131.70%,"$2,650.70","$1,408.20",159,"11,000",-